### ISSUE TITLE
Use the node and npm local if version match

### ISSUE THREAD

**Issue by cesarlarsson** [eirslett/frontend-maven-plugin#604] opened 2017-05-15 22:34 UTC
If there a way to use the local npm and node version and no download and create the node folder with those files if we have already installed the version on my local environment?

**Comment by eirslett** [comment] 2017-05-15 22:51
Closing this issue as a duplicate of #54 #108 #177 #243 #273 #277 #340 #344 #440 #471 :wink:

**Closed by eirslett** 2017-05-15 22:51 UTC

**Comment by sorin7486** [comment] 2017-05-19 12:35
Your philosophy sucks, mate. I must of seen 20 issues opened about this and you keep saying no, just because if you do things a certain way everybody else is expected to. Yeah, I'll be using exec instead.

**Comment by jollytoad** [comment] 2017-05-19 12:52
That's exactly the point, if you already have the tools installed you don't need this, just do it with exec. The primary purpose of this plugin (as I understand it) is to download local isolated copies of the JS tools for projects whose primary build pipeline is based around Java tooling.

**Comment by qacwnfq** [comment] 2017-05-21 11:38
Why would you ever want to use local installation over the one the plugin provides? It's much more stable to control the versions in the pom.xml then to leave it up to devs to keep track.
I worked on a project with legagy code and new code where two modules required different node versions to run correctly for some time. Keeping the node versions in the pom.xml files really prevented a lot of headache. It allows you to update your huge projects module by module instead of doing it all at once and breaking everything.

**Comment by ppkarwasz** [comment] 2025-04-12 19:26
We use Node.js only to generate our website, which 99% of the times is built and deployed on a GitHub runner that comes with Node.js preinstalled.

While technically we could use `exec-maven-plugin` or a profile that switches between `exec-maven-plugin` and `frontend-maven-plugin`, we prefer to use the latter, since it guarantees that:

- Contributors can also generate the website, without necessarily having to install Node.js first.
- We have a reproducible website, since the version of Node.js is fixed in the POM. If the GitHub runner changes Node.js version, we'll still use the specified version.

However the usage of `frontend-maven-plugin` is not ideal, since we have around 50 MiB of additional data in our Maven cache.

@eirslett, would you be open to making `NodeExecutor` and other services in your plugin injectable Sisu components?

If `NodeExecutor` was managed by Maven's dependency injection, users could provide their own implementations that would look for `node` with the appropriate version on the system `PATH` first.
