### ISSUE TITLE
<installDirectory> ignored/purpose?

### ISSUE THREAD

**Issue by Katharsas** [eirslett/frontend-maven-plugin#291] opened 2015-09-24 16:48 UTC
My pom (part) looks like this:
```
<configuration>
	<workingDirectory>src/main/frontend</workingDirectory>
</configuration>
<execution>
	<id>install node and npm</id>
	<goals>
		<goal>install-node-and-npm</goal>
	</goals>
	<configuration>
		<nodeVersion>v4.1.1</nodeVersion>
		<npmVersion>3.3.3</npmVersion>
		<nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
		<npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
		
		<installDirectory>target</installDirectory>
	</configuration>
</execution>
```
I also tried `.` instead of `target`, result is the same: Installation works fine, but any executions still try to find npm in `workingDirectory/node`, in my case `src/main/frontend/node` instead of `target/node` (which of course causes error `java.io.IOException: Cannot run program "...\src\main\frontend\node\node.exe"`).

Is it possible to seperate the node installation (using installDirectory) from the working directory or is that not intended to work?

**Comment by eirslett** [comment] 2015-09-25 18:15
Yes, it's intended to work. So you've probably hit a bug!

**Comment by kkarwows** [comment] 2015-10-01 12:46
+1 - same issue

**Comment by DanieleTorino** [comment] 2015-10-01 14:18
It's working for me. But I have the working directory set to `target/frontend` because IMHO the `src` should not contain any automatically generated files. So what I do is copy the required files from `src/main/frontend` to `target/frontend` using the maven-resources-plugin before running the frontend build.

This is my configuration for the maven-resources-plugin:

			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-frontend-resources</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.basedir}/target/frontend</outputDirectory>
							<resources>
								<resource>
									<directory>${project.basedir}/src/main/frontend</directory>
									<filtering>false</filtering>
									<excludes>
										<exclude>README.txt</exclude>
										<exclude>package.json</exclude>
										<exclude>bower.json</exclude>
									</excludes>
								</resource>
								<resource>
									<directory>${project.basedir}/src/main/frontend</directory>
									<filtering>true</filtering>
									<includes>
										<include>package.json</include>
										<include>bower.json</include>
									</includes>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>

This is my configuration for the frontend-maven-plugin in the parent pom (pluginManagement):

	<plugin>
		<groupId>com.github.eirslett</groupId>
		<artifactId>frontend-maven-plugin</artifactId>
		<version>${build.plugin.frontend-maven-plugin.version}</version>
		<configuration>
			<installDirectory>target</installDirectory>
			<workingDirectory>target/frontend</workingDirectory>
			<nodeDownloadRoot>http://nodejs.org/dist/</nodeDownloadRoot>
			<npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
			<nodeVersion>v0.12.7</nodeVersion>
			<npmVersion>2.14.2</npmVersion>
		</configuration>
	</plugin>

**Comment by eirslett** [comment] 2015-10-01 16:18
@klieber have you come across this yet?

**Comment by klieber** [comment] 2015-10-01 16:48
@Katharsas, this is working as designed, you just have your configuration wrong.  If you put the install directory at the execution level then none of the other executions know about it.

For instance, with a config like this:

```xml
<configuration>
  <workingDirectory>src/main/frontend</workingDirectory>
</configuration>
<executions>
  <execution>
    <id>install node and npm</id>
    <goals>
      <goal>install-node-and-npm</goal>
    </goals>
    <configuration>
      <nodeVersion>v4.1.1</nodeVersion>
      <npmVersion>3.3.3</npmVersion>
      <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
      <npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
      <installDirectory>target</installDirectory>
    </configuration>
  </execution>
  <execution>
    <id>install npm modules</id>
    <goals>
      <goal>npm</goal>
    </goals>
  </execution>
</executions>
```

When the `install-node-and-npm` goal runs it will have a working directory set to `src/main/frontend` and install directory set to `target` so node will be installed under `target/node`.  However, when the `npm` goal runs since there is no `<installDirectory/>` set the plugin will use the default which is the working directory so the working directory is set to `src/main/frontend` and the install directory is set to `src/main/frontend`.

Moving the `<installDirectory />` up next to the `<workingDirectory />` will ensure that all executions know about it.

```xml
<configuration>
  <workingDirectory>src/main/frontend</workingDirectory>
  <installDirectory>target</installDirectory>
</configuration>
<executions>
  <execution>
    <id>install node and npm</id>
    <goals>
      <goal>install-node-and-npm</goal>
    </goals>
    <configuration>
      <nodeVersion>v4.1.1</nodeVersion>
      <npmVersion>3.3.3</npmVersion>
      <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
      <npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
    </configuration>
  </execution>
  <execution>
    <id>install npm modules</id>
    <goals>
      <goal>npm</goal>
    </goals>
  </execution>
</executions>
```

Your other option is to just use one execution.  This is how I do it because it's less lines of xml.  The only reason to really have multiple executions is if I don't like the default phase for each of the goals:

```xml
<executions>
  <execution>
    <goals>
      <goal>install-node-and-npm</goal>
      <goal>npm</goal>
    </goals>
    <configuration>
      <nodeVersion>v4.1.1</nodeVersion>
      <npmVersion>3.3.3</npmVersion>
      <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
      <npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
      <workingDirectory>src/main/frontend</workingDirectory>
      <installDirectory>target</installDirectory>
    </configuration>
  </execution>
</executions>
```

**Comment by Katharsas** [comment] 2015-10-04 12:52
Okay thanks alot for the nice explanation. I will try that out.

**Comment by eirslett** [comment] 2015-10-06 07:23
I'll close this one, feel free to reopen if the advice doesn't help! (Would be even better with some documentation for it written in the wiki, maybe)

**Closed by eirslett** 2015-10-06 07:23 UTC
