### ISSUE TITLE
color on console

### ISSUE THREAD

**Issue by dokuboyejo** [eirslett/frontend-maven-plugin#180] opened 2015-03-23 12:42 UTC
How can the default argument option --color=false be changed.
I will like to have a colored output log

**Comment by eirslett** [comment] 2015-04-02 11:30
In the early stages of this plugin, it was decided to remove all colors from the log, because it interfered with build servers that couldn't show colors and instead showed strange artifacts/symbols.
It might make sense to eigher (1) re-add colors as the default option or (2) add a <colors>true/false</colors> option. The problem is that each runner (grunt, gulp, bower...) has its own way of specifying colors or not, with different names for the flags.
I'd be happy to merge a PR that adds a <colors> property! But for now I'll close this issue.

**Closed by eirslett** 2015-04-02 11:30 UTC

**Comment by jgangemi** [comment] 2015-04-02 20:14
this is still open in #122. 

i haven't looked at what's going on in the code as of late, but why not just remove whatever forces the colors to be off and let the users specify to turn them on in the args?

**Comment by eirslett** [comment] 2015-08-21 21:54
Initially, it was turned off because many logs were showing strange characters instead of colors (the ones without color support).
