### ISSUE TITLE
com.github.eirslett:frontend-maven-plugin:1.3:webpack (webpack build) on project blog: Failed to run task

### ISSUE THREAD

**Issue by johnwcv** [eirslett/frontend-maven-plugin#566] opened 2017-02-14 12:32 UTC
Hi.
I am getting this error executing an application with Maven.

What should I do?
Thanks in advance

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:webpack (webpack build) on project blog: Failed to run task: 'webpack.js --config webpack/webpack.dev.js' failed. (error code 2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:webpack (webpack build) on project blog: Failed to run task
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 31 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'webpack.js --config webpack/webpack.dev.js' failed. (error code 2)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
        at com.github.eirslett.maven.plugins.frontend.mojo.WebpackMojo.execute(WebpackMojo.java:64)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
        ... 33 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by mriehema** [comment] 2017-02-15 12:04
Please mention your frontend-maven-plugin, operating system, java and maven version.

**Comment by johnwcv** [comment] 2017-02-15 13:28
frontend-maven-plugin: 1.3
operating system: Windows 10
Java: 1.8
Maven: 3.3.9

**Comment by benkuly** [comment] 2017-02-28 09:07
same problem here

**Comment by hagaisela** [comment] 2017-02-28 13:38
same here:
frontend-maven-plugin: 1.3
operating system: Ubuntu 16.04
Java: 1.8
Maven: 3.3.9

**Comment by rachmatfahmiaziz** [comment] 2017-10-16 07:29
any clue?
i have the same error here, i'm following tutorial spring and react (https://spring.io/guides/tutorials/react-and-spring-data-rest/)

Failed to run task (com.github.eirslett:frontend-maven-plugin:1.2:webpack:webpack build:generate-resources)

org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'webpack.js ' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60)
	at com.github.eirslett.maven.plugins.frontend.mojo.WebpackMojo.execute(WebpackMojo.java:64)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89)
	... 32 more

**Comment by felipewmartins** [comment] 2017-10-18 01:26
I have the same problem.

`Failed to run task (com.github.eirslett:frontend-maven-plugin:1.2:webpack:webpack build:generate-resources) 
 org.apache.maven.plugin.MojoFailureException: Failed to run task at 
 com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:95) at 
 org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360) at 
 org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:
 52) at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200) at 
 org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735) at 
 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246) at 
 org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301) at 
 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304) at 
 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360) at 
 org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383) at 
 org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144) at 
 org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235) at 
 org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) Caused by: 
 com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'webpack.js ' failed. (error code 1) at 
 com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:60) at 
 com.github.eirslett.maven.plugins.frontend.mojo.WebpackMojo.execute(WebpackMojo.java:64) at 
 com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:89) ... 
 32 more`

**Comment by mguella** [comment] 2017-10-19 14:27
I had the same problem...
Seems like this happens when the execution of webpack fails.
Maybe when a task fails would be cleaner to print the stdout of the task process instead of the Java exception.

Solved (in my case) by running manually webpack (from the folder defined in `workingDirectory`) and fixing the errors shown in stdout.

```
./node/node ./node_modules/webpack/bin/webpack.js
```

**Comment by nahuelvr** [comment] 2017-10-30 18:21
Have you tried `mvn clean install` and check what happens? I was also following the React.js and Spring Data REST Tutorial and I had the same error after `mvn clean` (that deletes the `target` directory). My output error was: 
`Cannot run program "my-path/rest-service/target/node/node" (in directory "my-path/rest-service"): error=2, No such file or directory`
After `mvn clean install` the error doesn't appear anymore.

**Comment by jlarroque** [comment] 2018-01-29 00:54
Running mvn clean install indeed helps, as suggested by nahuelvr. I detected that the files package.json and webpack.config.js should be created, otherwise won't be frontend at all. Too bad that the tutorial doesnt't mention it.

**Comment by timkao** [comment] 2018-04-18 18:44
The problem is solved after creating

- webpack.config.js
- package.json 

Thanks @jlarroque

**Comment by aliahsan07** [comment] 2018-06-29 10:49
where do we have to keep these files?

**Comment by shlou** [comment] 2018-09-24 16:35
@jlarroque thanks, working for me.

**Comment by nsbrno** [comment] 2019-02-28 18:28
in my case resolved by adding the property below in the file `packege.json`
```
"devDependencies": {
    "webpack": "^4.29.6"
  }
```

**Comment by tamerrab2003** [comment] 2019-03-27 15:28
upgrading node to version v10.15.3 and npm to version 6.4.1 fixed the issue
I hope this helps

**Comment by dziemich** [comment] 2019-03-29 14:34
As @mguella suggested earlier this issue happens because of webpack execution error. Running `npx webpack` helps tremendously with debugging the error.

**Comment by fgbogdan** [comment] 2019-05-24 14:14
missing - uriListConverter.js and uriTemplateInterceptor.js from /src/main/js/api

**Closed** 2019-05-26 16:57 UTC

**Comment by cesarbruno16** [comment] 2019-09-08 03:45
> in my case resolved by adding the property below in the file `packege.json`
> 
> ```
> "devDependencies": {
>     "webpack": "^4.29.6"
>   }
> ```

this resolve for me too

**Comment by gillianbc** [comment] 2020-01-21 21:33
> where do we have to keep these files?

I think I'm following the same tutorial - https://spring.io/guides/tutorials/react-and-spring-data-rest/.  In the root of the project, I created package.json and webpack.config.json.  I created stc/main/js/app.js  (blank file) and then I could do a **mvn clean install** successfully.

**Comment by JesseYentsch** [comment] 2020-04-28 16:38
If you're following https://spring.io/guides/tutorials/react-and-spring-data-rest/ making a package.json and a webpack.config.js file worked for me as long as I added 
`"devDependencies": {
    "webpack": "^4.29.6"
  }`
in the package.json as @nsbrno mentioned. 

You should also make sure that the  correct executions are added to the plugin if you are using https://github.com/eirslett/frontend-maven-plugin. Once thats finished, run a `mvn clean install` and it should work.
