### ISSUE TITLE
Possibility to change folder name ./node 

### ISSUE THREAD

**Issue by publicocean0** [eirslett/frontend-maven-plugin#167] opened 2015-03-04 16:20 UTC
Ability to change the folder name 'node' where is saved npm in another folder defined in the configuration. It permits to hidden node for example in a hidden folder .node for example or to recall a folder shared among different projects or sub maven modules or possibility to point at the linux system folder for example. The developer can decide what to do.

**Comment by publicocean0** [comment] 2015-03-04 16:24
Anyway i decide to use yoour plugin with my grunt plugin https://github.com/publicocean0/grunt-resourcesbinder. I hope to can introduce soon this new features. Bye

**Comment by eirslett** [comment] 2015-03-05 08:48
Yes, it has been mentioned before, many people want to be able to change the "node" directory. But it's a significant rewrite.
It's good to hear you found my plugin usable! I'll close this issue as it seems to be a duplicate of #18.

**Closed by eirslett** 2015-03-05 08:48 UTC
