### ISSUE TITLE
Issue in install node and npm

### ISSUE THREAD

**Issue by kelele0225** [eirslett/frontend-maven-plugin#279] opened 2015-09-10 08:31 UTC
Hi,

The default download root using http is not worked now, should use https now.
When running the goal "install node and npm" by default it will download installation file from address like "http://nodejs.org/dist/v0.10.31/node-v0.10.31-linux-x86.tar.gz", but this url will be redirected to "https://nodejs.org/en/blog/" so the downloaded file is actually a html file.
Then later extract will fail.
We can work around this by configuring download root in the plugin configuration but we think the plugin should fix this by correcting the default download protocol to "https"

**Comment by ddotpdot** [comment] 2015-09-10 09:24
@kelele0225 reproduced this getting : Input is not in the .gz format .
The download root workaround doesn't help

**Comment by SlevinBE** [comment] 2015-09-10 09:36
duplicate of #278

**Closed** 2015-09-11 12:06 UTC
