### ISSUE TITLE
npmRegistryURL parameter does not work like i expect it to

### ISSUE THREAD

**Issue by jgangemi** [eirslett/frontend-maven-plugin#356] opened 2016-01-29 21:05 UTC
it appears the newly added `npmRegistryURL` needs to be set via system property and is not read directly out of the pom configuration and passed into `DefaultNpmRunner`.

can this be changed? i'm happy to submit a PR

**Comment by eirslett** [comment] 2016-01-30 17:49
I'll, close this as a duplicate of #357 .

**Closed by eirslett** 2016-01-30 17:49 UTC
