### ISSUE TITLE
Cannot find module Gulp when change workingDirectory

### ISSUE THREAD

**Issue by sinneren** [eirslett/frontend-maven-plugin#590] opened 2017-04-14 12:24 UTC
It works fine, but I change workinDirectory(for node_modules, right?) from default and now it's crashed, because tried to find modules in installDirectory(for node only, right?). How to fix it?

**Comment by niklaushug** [comment] 2017-05-12 12:24
Having the same issue when workingDirectory and installDirectory are defined differently. 

[INFO] Running 'gulp ensure_theme_base -c abc' in /Users/tocco/Tests/maven-test/scenario-2/preprocessor
[ERROR] Error: Cannot find module '/Users/tocco/Tests/maven-test/scenario-2/.external-resources/node_modules/gulp/bin/gulp'
[ERROR]     at Function.Module._resolveFilename (module.js:469:15)
[ERROR]     at Function.Module._load (module.js:417:25)
[ERROR]     at Module.runMain (module.js:604:10)
[ERROR]     at run (bootstrap_node.js:393:7)
[ERROR]     at startup (bootstrap_node.js:150:9)
[ERROR]     at bootstrap_node.js:508:3

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>secenario-2</groupId>
  <artifactId>secenario-2</artifactId>
  <version>1.0-SNAPSHOT</version>

  <build>
    <plugins>
      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>1.4</version>

        <configuration>
          <nodeVersion>v6.10.2</nodeVersion>
          <workingDirectory>${session.executionRootDirectory}/preprocessor</workingDirectory>
          <installDirectory>${session.executionRootDirectory}/.external-resources</installDirectory>
        </configuration>

        <executions>
          <execution>
            <id>install-node-and-npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
          </execution>

          <execution>
            <id>npm-install</id>
            <goals>
              <goal>npm</goal>
            </goals>
            <configuration>
              <arguments>install</arguments>
            </configuration>
          </execution>

          <execution>
            <id>ensure-theme-base</id>
            <goals>
              <goal>gulp</goal>
            </goals>
            <configuration>
              <arguments>ensure_theme_base -c abc</arguments>
            </configuration>
          </execution>

          <execution>
            <id>build-assets-with-gulp</id>
            <goals>
              <goal>gulp</goal>
            </goals>
            <configuration>
              <arguments>build -m production -c abc</arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>

**Comment by awpya** [comment] 2017-05-23 05:36
This error is caused by commit 0ac13e5 due to issue https://github.com/eirslett/frontend-maven-plugin/issues/536. The change of dropping .js from gulp.js in constant TASK_LOCATION and the new lookup mechsnism in NodeTaskExecutor .getAbsoluteTaskLocation which is first checking if a file named "node_modules/gulp/bin/gulp" is available in the working directory is causing this error. In the working directory there is a gulp.js NOT a gulp file and in installation directory is no gulp file.

Reverting commit 0ac13e5 will fix this issue.

**Comment by alex-courtis** [comment] 2017-10-12 04:46
Hi

Please merge this issue and release the plugin - it's blocking gulp execution )-:

**Comment by eirslett** [comment] 2017-10-13 10:08
Closed as duplicate

**Closed by eirslett** 2017-10-13 10:08 UTC
