### ISSUE TITLE
libsass bindings not found

### ISSUE THREAD

**Issue by noherczeg** [eirslett/frontend-maven-plugin#251] opened 2015-07-26 15:33 UTC
In our project we use grunt-sass (1.0.0), which requires node-sass. The build process is okay when we run it in native node context, but when we try to run it with the forontend-maven-plugin it fails with the following message:

[INFO] >> Error: `libsass` bindings not found in E:\work\xyz\project\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64-14\binding.node. Try reinstalling `node-sass`?

It of course uses a fresh install.

I'm using:
- node v0.12.2
- npm v2.7.4

Any suggestions?

**Comment by noherczeg** [comment] 2015-07-26 15:35
I'm on Windows btw.

**Comment by ccit-spence** [comment] 2015-07-26 18:51
Just had the exact same error.  On a Mac.  Same here a fresh install is a temp fix.

**Comment by noherczeg** [comment] 2015-07-26 20:56
No kind of reinstall fixed this for me :(

**Comment by ccit-spence** [comment] 2015-07-26 21:22
Did you try deleting the `node_modules` directory?  Let it rebuild via the plugin.

**Comment by noherczeg** [comment] 2015-07-26 21:51
Of course, but I moved to a more crucial task now. If I'm not mistaken my co-worker managed to do the build process on his machine somehow, I'll ask him about it tomorrow. If there is a solution, then I'll surely post it here, in case it'll be useful for others in the future :)

**Comment by ccit-spence** [comment] 2015-07-30 07:58
I have noticed that I am seeing this error in a lot of places other than this project.  I don't think it is related to the plugin specifically.  More the node-sass library itself.  https://github.com/sass/node-sass/issues/918

**Comment by mriehema** [comment] 2015-08-14 11:55
We're having the same problem. I could reproduce it with node/npm installed on my machine (win x64). It is caused by the different versions of node/npm defined in the pom.xml using this plugin and my local installation. 

our plugin wanted to use (node 0.10.x):
\project\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64**-11**\binding.node. 
My installation wants to use (node 0.12.x):
\project\node_modules\grunt-sass\node_modules\node-sass\vendor\win32-x64**-14**\binding.node. 

And we had the same issue with Mac OSX. Our solutition is to update both node/npm to the same version and to delete node_modules before running this plugin.

**Comment by mriehema** [comment] 2015-08-14 12:24
#249 looks like a fix for this issue.

**Comment by eirslett** [comment] 2015-08-21 21:42
I just released a new version that is supposed to fix it. Tell me if it still doesn't work!

**Closed by eirslett** 2015-08-21 21:42 UTC

**Comment by noherczeg** [comment] 2015-08-22 19:21
I'll look into it, monday tops.

**Comment by mmehta4** [comment] 2015-09-15 06:14
in which version the issue "libsass bindings not found" is fixed. I am using 0.0.25 but i am still getting this error. i have also checked node/npm version local and global.Both are same. But still getting the error.

**Comment by mriehema** [comment] 2015-09-15 08:32
Version 0.0.25. Delete node_modules and node folders and try again. Maybe you have still the wrong libsass binaries.

**Comment by mmehta4** [comment] 2015-09-15 16:50
It working for me now. Thanks.
