### ISSUE TITLE
How can we use frontend-maven-plugin to install and execute `yarn`

### ISSUE THREAD

**Issue by amandogra** [eirslett/frontend-maven-plugin#495] opened 2016-10-19 18:25 UTC
**Do you want to request a _feature_ or report a _bug_?**
It is a feature request

**What is the current behavior?**
Unable to install or execute [yarn] (https://code.facebook.com/posts/1840075619545360)

**If the current behavior is a bug, please provide the steps to reproduce.**
It's not a bug, as there is no 'goal' in the plugin to handle 'yarn' yet.

**What is the expected behavior?**
To be able to add following in the pom.xml and execute while building maven.
```
    <execution>
	<id>execute yarn</id>
	<goals>
		<goal>yarn</goal>
	</goals>
    </execution>
```
**Please mention your frontend-maven-plugin and operating system version.**
LATEST
macOS Seira [macOS 10.12 (16A323)]

**Comment by eirslett** [comment] 2016-10-19 18:29
This issue is a duplicate of #490 (which has an example for usage) and #492.

**Closed by eirslett** 2016-10-19 18:29 UTC
