### ISSUE TITLE
Temp files should be stored in target (${project.build.directory}) folder

### ISSUE THREAD

**Issue by andham** [eirslett/frontend-maven-plugin#156] opened 2015-02-10 07:43 UTC
Any temporary file shouldn't be stored in the project's root folder (or whatever you configure the working directory to) but rather in Maven's build directory (typically 'target'). In cases where these temp files aren't cleaned up, it's much better that they are left there than somewhere else.

One example is NodeAndNPMInstaller.installNpm() where the removal of the npm.tar.gz file could be skipped if the extraction of the file fails. Leaving stuff in the Maven project's (root) folder is not a good thing! That's what the target folder is for.

**Comment by cameroncan** [comment] 2015-03-10 19:20
I agree with not storing everything in source, including all of the npm dependencies. But I'm not sure that storing it in the target directory is the best solution either. Since grunt introduces a separate build process with its own work files, it calls for its own work directory.

One of the nice things in maven is that you can do a true build from scratch by simply deleting the target directory. But the grunt process downloads all of the dependencies locally (no local repository comparable to maven's) and I want to keep those files around longer. I want to be able to control when to do a clean build for my java files (maven) and when to do a clean build for my frontend (grunt), and not mix the two. So far, I like the approach of the grunt maven plugin, which does this approach (https://github.com/allegro/grunt-maven-plugin). 

What I propose instead is that the js source directory is copied to a "target-grunt" folder (a sibling to maven's target folder) and then that becomes the working directory for npm and grunt. Then grunt can copy any final artifacts to where they need to go for the maven distribution.

In either case though, I think this should be a configurable option (i.e. the work directory)

**Comment by cameroncan** [comment] 2015-03-10 19:26
I just saw that this is discussed a bit in #18.

**Comment by eirslett** [comment] 2015-03-10 22:57
Yup, I'll close this as a duplicate of #18.

**Closed by eirslett** 2015-03-10 22:57 UTC
