### ISSUE TITLE
Maven displays npm logs as errors

### ISSUE THREAD

**Issue by jeerbl** [eirslett/frontend-maven-plugin#411] opened 2016-05-04 15:48 UTC
I set the loglevel to `http` for my `npm install`. When `npm install` gets executed by the Maven Frontend Plugin, it is displayed as `[ERROR]` instead of `[INFO]`.

Partial log below:

```
15:36:22 [INFO] Running 'npm --userconfig D:\sf\p2\sf-jobs\7942d5cf032b28f7\mockups\.npmrc install --no-optional' in D:\sf\p2\sf-jobs\7942d5cf032b28f7\mockups
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//bless
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//body-parser
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//bower
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//bower-art-resolver
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//commander
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//connect-gzip
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//del
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//express
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//fastclick
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//file
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//findup-sync
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//fontfaceobserver
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//glob
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-add-src
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-angular-htmlify
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-angular-templatecache
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-bless
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-changed
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-concat
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-debug
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-directory-map
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-help
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-htmlmin
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-if
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-livereload
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-ng-annotate
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-rename
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-replace
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-sass
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-sourcemaps
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-uglify
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-util
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//gulp-webserver
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//jasmine-core
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//jsdoc
15:36:28 [ERROR] npm http request GET https://registry.npmjs.org//karma
```

Do you think it is related to Maven or the Frontend plugin? Or is it NPM returning wrong code?

**Comment by eirslett** [comment] 2016-05-04 20:09
It's probably npm writing to stderr for some reason.

**Comment by jonesbusy** [comment] 2016-05-09 17:15
Same issue for me.

But sadly npm seems to log http level  to stderr...

```
$ npm install > out 2> err & tail -n 2000 -f err
```

**Comment by newbearclaw** [comment] 2016-10-16 17:39
I have the same problem my packages are getting downloaded fine but these errors are raising questions.
More confusing part of it is that I have specified a private registry in my project level .npmrc. What these log messages are showing a different npm registry.
I am not sure which registry is getting used to download the modules.

**Comment by dlabey** [comment] 2017-02-01 21:17
Anyone able to fix this? Same thing is happening, I have tried setting the logstream to process.stdout and that didn't solve it either.

**Comment by mriehema** [comment] 2017-02-02 10:11
You could open a pull request for this with a similiar fix like in https://github.com/eirslett/frontend-maven-plugin/pull/380

**Comment by dlabey** [comment] 2017-02-02 17:57
Interesting... what if instead of implicitly assuming its an error only assume its an error if npm ERROR occurs? I think the explicit assuming would be more ideal to most?

**Comment by eirslett** [comment] 2017-02-02 20:45
This is something that should be fixed in npm, it doesn't make sense that it logs stuff to stderr if it's not errors.

**Comment by apaatsio** [comment] 2017-02-17 10:50
stderr can be used to log all kinds of diagnostic output. I'm not saying it's a good (or a bad) thing but that's the status quo. Exit status is the standard way to detect if a process has failed or not.

**Comment by eirslett** [comment] 2017-02-17 12:15
At least as far as this plugin is concerned, all it does is forward stdout to Maven's stdout, and stderr to Maven's stderr. I'd say it's a feature, not a bug.

**Closed by eirslett** 2017-02-17 12:15 UTC
